export const SERVICE_NAMES = {
  AUTH_USER: 'AUTH_USER_SERVICE',
  MOVIE: 'MOVIE_SERVICE',
  CINEMA_SHOWTIME: 'CINEMA_SHOWTIME_SERVICE',
  BOOKING: 'BOOKING_SERVICE',
  PAYMENT: 'PAYMENT_SERVICE',
  TICKET: 'TICKET_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
  PRODUCT: 'PRODUCT_SERVICE'
} as const;

export const ServiceNames = {
  authUser: SERVICE_NAMES.AUTH_USER,
  movie: SERVICE_NAMES.MOVIE,
  cinemaShowtime: SERVICE_NAMES.CINEMA_SHOWTIME,
  booking: SERVICE_NAMES.BOOKING,
  payment: SERVICE_NAMES.PAYMENT,
  ticket: SERVICE_NAMES.TICKET,
  notification: SERVICE_NAMES.NOTIFICATION,
  product: SERVICE_NAMES.PRODUCT
} as const;
